Various cleanups, add SSL/timeout configuration to HTTPJSON, log collector errors
lightstep/lightstep-tracer-ruby pull request #66
Opened 2018-09-11 14:02 UTC by splittingred

## What?

* Adds .rubocop.yml to make this library more IDE-friendly
* Bumps simplecov to 0.16 to get past Fixnum errors in Ruby 2.4
* Logs errors to the logger when the reporter fails to flush to the collector
* Uses `.is_a?` instead of `===` for type comparison
* Freezes string constants in the HTTPJSON transport

Also adds the following options to the HTTPJSON transport, which are passed to the underlying Net::HTTP adapter:

* ssl_verify_peer
* open_timeout
* read_timeout
* continue_timeout
* keep_alive_timeout

This is based on our extensive use of the library, and is moving some of the logic in our extension of this library back upstream: https://github.com/bigcommerce/bc-lightstep-ruby

----

Thanks!

2018-09-13 00:02 UTC, sbaum1994 commented
Shaun, just letting you know this is queued up for one of our engineers to review. We really appreciate the contribution, thank you 👍👍

2018-09-17 23:03 UTC, krishicks requested changes

2018-09-17 23:03 UTC, krishicks commented on lib/lightstep/transport/http_json.rb
> +          if @port == 443
Unless I'm wrong, this constraint is new.

I would remove this conditional for two reasons:

1. It could be surprising code because there's nothing that says it will only do TLS for port 443; just that the defaults are 443 and TLS
2. There's nothing saying you have to listen on 443 for TLS. The caller can now not use any other port with TLS.

2018-09-18 14:09 UTC, splittingred commented on lib/lightstep/transport/http_json.rb
> +          if @port == 443
@krishicks Good point. Will fix.

2018-09-18 14:11 UTC, splittingred commented
@krishicks Thanks! ♻️ 🙇

2018-09-18 15:07 UTC, krishicks approved these changes

2018-09-18 17:24 UTC, merged